# Generated by Django 2.1.1 on 2018-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardTags', models.CharField(max_length=200)),
            ],
        ),
    ]
