# Generated by Django 2.0.2 on 2018-09-20 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoteDeatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asq_app.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asq_app.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
