# Generated by Django 2.0.2 on 2018-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0002_auto_20180921_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsearch',
            name='question_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tagsearch',
            name='question_slug',
            field=models.IntegerField(blank=True),
        ),
    ]
