# Generated by Django 2.0.2 on 2018-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0003_auto_20180921_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsearch',
            name='question_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
