# Generated by Django 2.0.2 on 2018-09-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0003_auto_20180921_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVoteDeatil',
            new_name='UserVoteDetail',
        ),
    ]
