# Generated by Django 2.0.2 on 2018-09-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0004_auto_20180921_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservotedetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
