# Generated by Django 2.0.2 on 2018-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0005_auto_20180921_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsearch',
            name='question_title',
            field=models.CharField(default='untitle question', max_length=200),
        ),
    ]
