# Generated by Django 2.0.8 on 2018-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asq_app', '0006_question_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='result',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='', max_length=1000, verbose_name='tags'),
        ),
    ]
